all: insertion-sort-benchmark merge-sort-benchmark quick-sort-benchmark gnome-sort-benchmark comb-sort-benchmark cocktail-sort-benchmark shell-sort-benchmark cycle-sort-benchmark

insertion-sort-benchmark: insertion-sort-benchmark.c Makefile
	gcc -Wall -o insertion-sort-benchmark insertion-sort-benchmark.c

merge-sort-benchmark: merge-sort-benchmark.c Makefile
	gcc -Wall -o merge-sort-benchmark merge-sort-benchmark.c

quick-sort-benchmark: quick-sort-benchmark.c Makefile
	gcc -Wall -o quick-sort-benchmark quick-sort-benchmark.c

gnome-sort-benchmark: gnome-sort-benchmark.c Makefile
	gcc -Wall -o gnome-sort-benchmark gnome-sort-benchmark.c

comb-sort-benchmark: comb-sort-benchmark.c Makefile
	gcc -Wall -o comb-sort-benchmark comb-sort-benchmark.c

cocktail-sort-benchmark: cocktail-sort-benchmark.c Makefile
	gcc -Wall -o cocktail-sort-benchmark cocktail-sort-benchmark.c
	
shell-sort-benchmark: shell-sort-benchmark.c Makefile
	gcc -Wall -o shell-sort-benchmark shell-sort-benchmark.c

cycle-sort-benchmark: cycle-sort-benchmark.c Makefile
	gcc -Wall -o cycle-sort-benchmark cycle-sort-benchmark.c
	