all: example-argument-parsing example-matrix-a example-matrix-b

example-argument-parsing: example-argument-parsing.c Makefile
	gcc -Wall -o example-argument-parsing example-argument-parsing.c

example-matrix-a: example-matrix-a.c Makefile
	gcc -Wall -o example-matrix-a example-matrix-a.c

example-matrix-b: example-matrix-b.c Makefile
	gcc -Wall -o example-matrix-b example-matrix-b.c

